In [59]:
import pandas as pd
import numpy as np
import random

Es el turno de los DataFrames

Crea un array de dos dimensiones con 4 filas y 3 columnas.

Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

Descarga el archivo "medallas" y carga el DataFrame.

Usando el loc extrae todas las columnas de la fila de Tailandia.

Usando el loc extrae todas las columnas de China e Irán.

Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

Usando el iloc extrae la información de la India. Devolved todas las columnas.

Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

Contesta a las siguientes preguntas:

¿Qué país consiguió más de 200 medallas de oro?

¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [4]:
array = np.empty((4,3))

In [9]:
df_paises = pd.DataFrame(array, columns= ["España", "Francia", "Italia"])
df_paises

          España        Francia         Italia
0  1.557438e-311  3.162020e-322   0.000000e+00
1   0.000000e+00   0.000000e+00  6.181662e+169
2  1.933350e+184  5.490736e+174  2.620486e+180
3   4.125781e-61   4.890210e-33   7.613529e-42

In [40]:
df_paises = pd.read_csv("medallas.csv", index_col=0)
df_paises.head(5)

            País   Oro  Plata  Bronce
1          China  1473    994     720
2          Japón  1032   1037     985
3  Corea del Sur   745    663     827
4           Irán   179    181     197
5     Kazajistán   155    158     224

In [24]:
df_paises.loc[7, "País"]

'Tailandia'

In [28]:
display(df_paises.loc[7, :])

País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [42]:
df_paises.columns

Index(['País', 'Oro', 'Plata', 'Bronce'], dtype='str')

In [41]:
df_paises.loc[(1,4), :]

    País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197

In [43]:
df_paises.loc[(1,4), "Oro":"Bronce"]

    Oro  Plata  Bronce
1  1473    994     720
4   179    181     197

In [47]:
df_paises["País"] == "India"

1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
Name: País, dtype: bool

In [48]:
df_paises[df_paises["País"] == "India"]

    País  Oro  Plata  Bronce
6  India  154    202     315

In [50]:
df_paises.iloc[5]

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object

In [51]:
df_paises.iloc[1::2, :]

               País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235

In [52]:
df_paises.iloc[1::2, 1:]

     Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235

In [53]:
df_paises["País"][df_paises["Oro"] > 200]

1            China
2            Japón
3    Corea del Sur
Name: País, dtype: str

In [55]:
df_paises["País"][(df_paises["Oro"] > 200) & (df_paises["Plata"] > 1000)]

2    Japón
Name: País, dtype: str

In [56]:
df_paises["País"][(df_paises["Oro"] > 200) | (df_paises["Bronce"] > 700)]

1            China
2            Japón
3    Corea del Sur
Name: País, dtype: str

In [57]:
df_paises["Total"] = df_paises["Oro"] + df_paises["Plata"] + df_paises["Bronce"]

In [58]:
df_paises.sample(5)

            País  Oro  Plata  Bronce  Total
4           Irán  179    181     197    557
3  Corea del Sur  745    663     827   2235
7      Tailandia  132    175     278    585
8      Indonesia  112    131     240    483
6          India  154    202     315    671

Momento de trabajar con Series. Contesta a las siguientes preguntas:

Crea dos listas:

Una que se llame "valores" que tenga 7 números aleatorios.

Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más información sobre este método aquí.

Crea una Serie con el diccionario creado en el punto anterior.

¿Qué forma tiene esta última Serie?

¿Qué tipo de datos tiene?

¿Qué tamaño tiene?

¿Cuáles son los índices de la Serie?

¿Y los values?

Extrae el valor para el índice "lunes"

Extrae el valor para el índice "lunes", "martes" y "miércoles".

Extrae el valor para el índice "lunes" y "domingo".

In [ ]:
valores = [random.randint(1, 100) for _ in range(7)]
print(valores)

[51, 58, 5, 4, 54, 61, 98]

In [66]:
indices = ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado", "domingo"]

In [67]:
laserie = pd.Series(valores, index= indices)
print(laserie)

lunes        51
martes       58
miercoles     5
jueves        4
viernes      54
sabado       61
domingo      98
dtype: int64

In [69]:
dicc = {}

for x in zip(valores, indices):
    dicc.update(x)

TypeError: cannot convert dictionary update sequence element #0 to a sequence